CREATE TABLE boards (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner INT NOT NULL,
    board_name VARCHAR(50) NOT NULL,
    description TEXT DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_board_name UNIQUE (board_name),
    CONSTRAINT fk_board_owner_id FOREIGN KEY (owner) REFERENCES users (id)
);

CREATE TABLE board_categories (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    board_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    description TEXT DEFAULT NULL,
    priority INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_bc_board_id FOREIGN KEY (board_id) REFERENCES boards (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TYPE board_permissions_enum AS ENUM (
    'CARD_CREATE',
    'CARD_UPDATE',
    'CARD_DELETE',
    'CARD_JOIN',
    'COMMENTS_CREATE',
    'COMMENTS_UPDATE',
    'COMMENTS_DELETE',
    'CATEGORIES_CREATE',
    'CATEGORIES_UPDATE',
    'CATEGORIES_DELETE',
    'BOARD_READ',
    'BOARD_UPDATE'
);

CREATE TABLE board_permissions (
    board_id INT NOT NULL,
    user_id INT NOT NULL,
    permission board_permissions_enum NOT NULL,

    CONSTRAINT pk_permission_unique PRIMARY KEY (board_id, user_id, permission),
    CONSTRAINT fk_bp_board_id FOREIGN KEY (board_id) REFERENCES boards (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_bp_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);
